[package]
name = "nine-spec"
version = "0.0.0"
authors = ["Casey Rodarmor <casey@rodarmor.com>"]
description = "9p Specification Parser"
license = "WTFPL"

[dependencies]
brev = "0.1.4"
regex = "0.1.73"
lazy_static = "0.2.1"
